import type { NewsArticle } from "./types"

export const mockNewsData: NewsArticle[] = [
  {
    id: "1",
    title: "Revolutionary AI Technology Transforms Healthcare Industry",
    description:
      "New artificial intelligence breakthrough promises to revolutionize medical diagnosis and treatment, offering unprecedented accuracy in detecting diseases.",
    content: "Full article content here...",
    url: "https://example.com/ai-healthcare",
    imageUrl: "/placeholder.svg?height=200&width=400",
    source: "TechNews Today",
    category: "technology",
    publishedAt: "2024-01-15T10:30:00Z",
    likes: 42,
  },
  {
    id: "2",
    title: "Global Markets Surge Following Economic Recovery Signs",
    description:
      "Stock markets worldwide show positive momentum as economic indicators suggest a strong recovery from recent downturns.",
    content: "Full article content here...",
    url: "https://example.com/markets-surge",
    imageUrl: "/placeholder.svg?height=200&width=400",
    source: "Financial Times",
    category: "business",
    publishedAt: "2024-01-15T09:15:00Z",
    likes: 28,
  },
  {
    id: "3",
    title: "Championship Finals Set Record Viewership Numbers",
    description:
      "The highly anticipated championship game breaks all previous viewership records, drawing millions of fans worldwide.",
    content: "Full article content here...",
    url: "https://example.com/championship-finals",
    imageUrl: "/placeholder.svg?height=200&width=400",
    source: "Sports Central",
    category: "sports",
    publishedAt: "2024-01-15T08:45:00Z",
    likes: 156,
  },
  {
    id: "4",
    title: "Breakthrough in Renewable Energy Storage Technology",
    description:
      "Scientists develop new battery technology that could solve the intermittency problem of renewable energy sources.",
    content: "Full article content here...",
    url: "https://example.com/renewable-energy",
    imageUrl: "/placeholder.svg?height=200&width=400",
    source: "Science Daily",
    category: "science",
    publishedAt: "2024-01-15T07:20:00Z",
    likes: 89,
  },
  {
    id: "5",
    title: "New Study Reveals Benefits of Mediterranean Diet",
    description:
      "Comprehensive research shows significant health improvements in participants following Mediterranean dietary patterns.",
    content: "Full article content here...",
    url: "https://example.com/mediterranean-diet",
    imageUrl: "/placeholder.svg?height=200&width=400",
    source: "Health Weekly",
    category: "health",
    publishedAt: "2024-01-15T06:00:00Z",
    likes: 73,
  },
  {
    id: "6",
    title: "Hollywood Blockbuster Breaks Opening Weekend Records",
    description:
      "The latest superhero movie shatters box office records with an unprecedented opening weekend performance.",
    content: "Full article content here...",
    url: "https://example.com/blockbuster-records",
    imageUrl: "/placeholder.svg?height=200&width=400",
    source: "Entertainment Weekly",
    category: "entertainment",
    publishedAt: "2024-01-14T22:30:00Z",
    likes: 234,
  },
  {
    id: "7",
    title: "Climate Summit Reaches Historic Agreement",
    description:
      "World leaders unite in unprecedented climate action plan, setting ambitious targets for carbon reduction.",
    content: "Full article content here...",
    url: "https://example.com/climate-summit",
    imageUrl: "/placeholder.svg?height=200&width=400",
    source: "Global News Network",
    category: "politics",
    publishedAt: "2024-01-14T20:15:00Z",
    likes: 167,
  },
  {
    id: "8",
    title: "Space Mission Discovers Potential Signs of Life",
    description:
      "Latest space exploration mission uncovers intriguing evidence that could indicate the presence of microbial life.",
    content: "Full article content here...",
    url: "https://example.com/space-life",
    imageUrl: "/placeholder.svg?height=200&width=400",
    source: "Space Explorer",
    category: "science",
    publishedAt: "2024-01-14T18:45:00Z",
    likes: 312,
  },
  {
    id: "9",
    title: "Tech Giant Announces Major Acquisition Deal",
    description:
      "Industry leader finalizes multi-billion dollar acquisition that will reshape the technology landscape.",
    content: "Full article content here...",
    url: "https://example.com/tech-acquisition",
    imageUrl: "/placeholder.svg?height=200&width=400",
    source: "Business Insider",
    category: "business",
    publishedAt: "2024-01-14T16:20:00Z",
    likes: 95,
  },
]
